version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: secret_santa
    environment:
      POSTGRES_DB: secret_santa
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: santa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
